title: Hololens Object Tracking Dataset
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-theme/cayman@v0.2.0
plugins:
- jekyll-remote-theme

